# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcloud-tui" do
  name "gcloud-tui"
  desc "Interactive terminal UI for Google Cloud Platform"
  homepage "https://github.com/joeazure/gcloud-tui"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcloud-tui"

  on_macos do
    on_intel do
      url "https://github.com/joeazure/app-releases/releases/download/v#{version}/gcloud-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/joeazure/app-releases"
      sha256 "59aa11c88ea4172c63b719dd24a4af8130156070f94c0817791ac543be14465d"
    end
    on_arm do
      url "https://github.com/joeazure/app-releases/releases/download/v#{version}/gcloud-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/joeazure/app-releases"
      sha256 "a3e2c3edbe709d5804502394b9a2ec3102c9989aebfda653005dec71b87a6576"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joeazure/app-releases/releases/download/v#{version}/gcloud-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/joeazure/app-releases"
      sha256 "00fc20579c1a3f50c8f163b94152744e7cba7a40e3540f0c7723c7a4870b61f9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcloud-tui"]
    end
  end

  # No zap stanza required
end
