# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcloud-tui" do
  name "gcloud-tui"
  desc "Interactive terminal UI for Google Cloud Platform"
  homepage "https://github.com/joeazure/gcloud-tui"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcloud-tui"

  on_macos do
    on_intel do
      url "https://github.com/joeazure/gcloud-tui/releases/download/v#{version}/gcloud-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/joeazure/gcloud-tui"
      sha256 "38f135a79057a4105a799f73101a7a15b5d831193c3f7ed9a33ecac3d21bb16a"
    end
    on_arm do
      url "https://github.com/joeazure/gcloud-tui/releases/download/v#{version}/gcloud-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/joeazure/gcloud-tui"
      sha256 "663c3c0ad164ef41b86427ce65b47e6ea745a4a75776c3b79b2930186eaa7fcc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joeazure/gcloud-tui/releases/download/v#{version}/gcloud-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/joeazure/gcloud-tui"
      sha256 "ab21ea0efce31ae18ba25f5a1f48b67f82621205670fe28e01d88d34f9cbf683"
    end
  end

  # No zap stanza required
end
