# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcloud-tui" do
  name "gcloud-tui"
  desc "Interactive terminal UI for Google Cloud Platform"
  homepage "https://github.com/joeazure/gcloud-tui"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcloud-tui"

  on_macos do
    on_intel do
      url "https://github.com/joeazure/app-releases/releases/download/v#{version}/gcloud-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/joeazure/app-releases"
      sha256 "53a45c9348449ae84e06a80adb93570116e86aefca8cddf0171dd632d3d62fee"
    end
    on_arm do
      url "https://github.com/joeazure/app-releases/releases/download/v#{version}/gcloud-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/joeazure/app-releases"
      sha256 "9be4e3c9f6c0cf9a4673c1214311346e7cb3bee2a07ef044e3607eb0db33982c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/joeazure/app-releases/releases/download/v#{version}/gcloud-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/joeazure/app-releases"
      sha256 "adeffb23a099f01f249b176d0b8584083532bbcb2ff8a35189bd06029c16c80b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcloud-tui"]
    end
  end

  # No zap stanza required
end
